# Generated by Django 6.0.6 on 2026-06-07 21:23

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('provider_name', models.TextField(blank=True, null=True)),
                ('license_number', models.TextField(blank=True, null=True)),
                ('license_holder', models.TextField(blank=True, null=True)),
                ('provider_type', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('status_date', models.TextField(blank=True, null=True)),
                ('sutq_rating', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('latitude', models.TextField(blank=True, null=True)),
                ('longitude', models.TextField(blank=True, null=True)),
                ('phone', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('provider_website', models.TextField(blank=True, null=True)),
                ('administrator', models.TextField(blank=True, null=True)),
                ('capacity', models.TextField(blank=True, null=True)),
                ('hours', models.TextField(blank=True, null=True)),
                ('ages_served', models.TextField(blank=True, null=True)),
                ('infant', models.TextField(blank=True, null=True)),
                ('toddler', models.TextField(blank=True, null=True)),
                ('preschool', models.TextField(blank=True, null=True)),
                ('school', models.TextField(blank=True, null=True)),
                ('county', models.TextField(blank=True, null=True)),
                ('scholarships_accepted', models.TextField(blank=True, null=True)),
                ('license_begin_date', models.TextField(blank=True, null=True)),
                ('license_expiration', models.TextField(blank=True, null=True)),
                ('languages', models.JSONField(blank=True, null=True)),
                ('deficiencies', models.JSONField(blank=True, null=True)),
                ('source_state', models.TextField(blank=True, db_index=True, null=True)),
                ('provider_url', models.TextField(blank=True, null=True)),
                ('state_data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('date', models.TextField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('original_status', models.TextField(blank=True, null=True)),
                ('corrective_status', models.TextField(blank=True, null=True)),
                ('status_updated', models.TextField(blank=True, null=True)),
                ('report_url', models.TextField(blank=True, null=True)),
                ('state_data', models.JSONField(blank=True, default=dict)),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='providers.provider')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
