# Generated by Django 6.0.6 on 2026-06-09 14:29

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('providers', '0002_pg_trgm_extension'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('relationship', models.CharField(choices=[('child', 'Child'), ('stepchild', 'Stepchild'), ('foster', 'Foster Child'), ('guardian_ward', 'Legal Guardian/Ward')], default='child', max_length=32)),
                ('in_school', models.BooleanField(default=False)),
                ('referral_need', models.CharField(choices=[('provider_active', 'Provider Active'), ('provider_chosen', 'Provider Chosen'), ('need_assistance', 'Need Assistance'), ('self_service', 'Self Service')], default='need_assistance', max_length=32)),
                ('care_schedule', models.JSONField(blank=True, default=dict)),
                ('active_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_in_care', to='providers.provider')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'children',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('institution_name', models.CharField(blank=True, max_length=255)),
                ('street', models.CharField(blank=True, max_length=255)),
                ('street_2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=128)),
                ('state', models.CharField(blank=True, max_length=64)),
                ('postal', models.CharField(blank=True, max_length=16)),
                ('grade_level', models.CharField(blank=True, max_length=64)),
                ('school_year_start', models.DateField(blank=True, null=True)),
                ('school_year_end', models.DateField(blank=True, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schools', to='referrals.child')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
