# Generated by Django 6.0.6 on 2026-06-09 15:00

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_pg_trgm_extension'),
        ('referrals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', models.CharField(choices=[('new', 'New'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('closed', 'Closed')], default='new', max_length=16)),
                ('source', models.CharField(choices=[('ingested', 'Ingested'), ('staff', 'Created by staff'), ('family', 'Created by family')], default='staff', max_length=16)),
                ('help_requested', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('external_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='referrals.child')),
                ('coordinator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_referrals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReferralProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', models.CharField(choices=[('suggested', 'Suggested'), ('shared', 'Shared with family'), ('selected', 'Selected'), ('declined', 'Declined')], default='suggested', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_referral_providers', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_links', to='providers.provider')),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_providers', to='referrals.referral')),
            ],
        ),
        migrations.AddField(
            model_name='referral',
            name='providers',
            field=models.ManyToManyField(related_name='referrals', through='referrals.ReferralProvider', to='providers.provider'),
        ),
        migrations.AddConstraint(
            model_name='referralprovider',
            constraint=models.UniqueConstraint(fields=('referral', 'provider'), name='uniq_referral_provider'),
        ),
        migrations.AddConstraint(
            model_name='referral',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('external_id',), name='uniq_referral_external_id_when_set'),
        ),
    ]
